config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users
  resources :items
  
  get 'welcome/index'
  get 'welcome/about'

  root to: 'welcome#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  validates :name, length: {minimum: 6}, presence: true
  
  def days_left
      (7 - (DateTime.now.to_date - created_at.to_date)).to_i
   end
  
  default_scope { order('created_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :items
  
 def admin?
   role == 'admin'
 end
 
 def moderator?
   role == 'moderator'
 end
  
  mount_uploader :avatar, AvatarUploader
  
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include Pundit
  
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end
 
   protected
 
   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
   end
  
  def after_sign_in_path_for(resource)
    @user = current_user
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  def index
    @items = current_user.items
    authorize @items
  end
  
  #def show  
   # @user = current_user
  # @item = Item.find(params[:id])
   # authorize @item
  #end
  
  def new
    
    @user = current_user
    @item = Item.new
    authorize @item
  end
  
  def create
   
    @user = current_user
    @item = current_user.items.build(item_params)
    authorize @item
    
    if @item.save(item_params)
      flash[:notice] = "Item was successfully created."
      redirect_to action: 'index'
      
    else
      flash[:alert] = "Error creating item."
      redirect_to action: 'index'
    end
  end
  
  def edit
    
    @user = current_user
    @item = Item.find(params[:id])
    authorize @item
  end
  
  def update
 
    @user = current_user
    @item = Item.find(params[:id])
    authorize @item
    
    if @item.update_attributes(item_params)
      flash[:notice] = "Item was successfully updated."
      redirect_to action: 'index'
      
    else
      flash[:alert] = "Error updating item."
      redirect_to action: 'index'
    end
  end
  
  def destroy
    @item = Item.find(params[:id])
    authorize @item
    
    if @item.destroy
      flash[:notice] = "Task complete!"
      
    else
      flash[:error] = "There was an error deleting the task. Please try again."
     
    end
    respond_to do |format|
       format.html
       format.js
     end
   end
  
  
  private
 
  def item_params
    params.require(:item).permit(:name, :details)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!
 
   def update
     if current_user.update_attributes(user_params)
       flash[:notice] = "User information updated"
       redirect_to edit_user_registration_path
     else
       flash[:error] = "Invalid user information"
       redirect_to edit_user_registration_path
     end
   end
  
  def show
     @user = User.find(params[:id])
    
  end
 
   private
 
   def user_params
     params.require(:user).permit(:name, :avatar)
   end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def dev_name
    'Joel Ramsey'
  end
  
  def form_group_tag(errors, &block)
     if errors.any?
       content_tag :div, capture(&block), class: 'form-group has-error'
     else
       content_tag :div, capture(&block), class: 'form-group'
     end
   end
  
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for item do |f| %>
<% if item.errors.any? %>
     <div class="alert alert-danger">
       <h4>There are <%= pluralize(item.errors.count, "error") %>.</h4>
       <ul>
         <% item.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
<%= form_group_tag(item.errors[:name]) do %>
<%= f.label :name %>
<%= f.text_field :name, class: 'form-control', placeholder: "Enter item name" %>
   <% end %>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/items/_item.html.erb
<div class="media"> 
  <div class="media-body">
    <h3>
    <% @items.each do |item| %>
      <div id="item-<%= item.id %>" >
      <small>
      <% if policy(item).edit? %>
        <%= link_to "", edit_item_path(item), class: 'glyphicon glyphicon-pencil' %>
      <% end %>
      <% if policy(item).destroy? %>
      | <%= link_to "", item, method: :delete, remote: true, class: 'glyphicon glyphicon-ok' %> |
      <% end %>
      </small>
      <span class="pull-center"><%= item.name %></span>  
      <small>
      <span class="pull-right">Days Remaining: <%= item.days_left %></span>
      </small>
      </br>
      </br>
  </div>
      <% end %>
      </h3>
    </div>
</div>

app/views/items/destroy.js.erb
<% if @item.destroyed? %>
$('#item-' + <%= @item.id %>).hide();
<% else %>
$('#item-' + <%= @item.id %>).prepend("<div class='alert alert-danger'><%= flash[:error] %></div>");
<% end %>

app/views/items/edit.html.erb
<h1>Edit Task</h1>
 
 <div class="row">
   <div class="col-md-8">
     <%= form_for @item do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter item:" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/items/index.html.erb
<h2><%= current_user.name %>'s Task List</h2>
<% if policy(Item.new).create? %>
<%= link_to "New", new_item_path, class: 'glyphicon glyphicon-plus' %>
<% end %>
<%= render partial: 'items/item' %>

app/views/items/new.html.erb
<h1>New Task</h1>
 
 <div class="row">
     <div class="col-md-8">
       <%= render partial: 'form', locals: { item: @item } %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
     <div class="container">
       <ul class="nav nav-tabs">
        <li><%= link_to "Bloccitoff", welcome_index_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
         <li><%= link_to "My Task List", items_path %></li> 
         <div class="pull-right user-info">
         
           <% if current_user %>
           <%= image_tag(current_user.avatar.tiny.url) if current_user.avatar? %>
             Hello <%= link_to (current_user.name || current_user.email), edit_user_registration_path %>! <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
           <% else %>
             <%= link_to "Sign In", new_user_session_path %> or
             <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
         </div>
         
      </ul>
      <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

<%= yield %>
  </div>

</body>
</html>

app/views/users/show.html.erb
<h2> User Details </h2>
<p>User Name: <%= @user.name %></p>
<p>User Email: <%= @user.email %></p>

app/views/welcome/about.html.erb
<h1> About Blocitoff </h1>
<p> Created by: <%= dev_name %> </p>

app/views/welcome/index.html.erb
<br/>
<div class="jumbotron">
  <h1>Bloccitoff</h1>
  <p>Bloccitoff is your solution for clean and secure to-do lists!</p>
  <p>
     <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
     <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>To Do Management</h2>
    <p>Easily keep track of your to-be-completed tasks.</p>
  </div>
  <div class="col-md-4">
    <h2>Self Destructing Lists</h2>
    <p>Fail to complete your task, and it dissapears after 7 days!</p>
  </div>
  <div class="col-md-4">
    <h2>Secure Your Schedule</h2>
    <p>Sign in to securely manage your personal task lists.</p>
  </div>
</div>